config:
  generic:
    existingSecret: "microgatewaysecrets"
imagePullSecrets:
  - name: "dockersecret"
redis:
  enabled: true
echo-server:
  enabled: true
ingress:
  enabled: true
readinessProbe:
  initialDelaySeconds: 30